name: passkeeper
description: A safe place to store all your passwords.
version: 1.1.3+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.1
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  provider: ^6.0.1
  google_sign_in: ^5.2.1
  font_awesome_flutter: ^9.2.0
  encrypt: ^5.0.1
  local_auth: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GentiumBook
      fonts:
        - asset: assets/fonts/GentiumBook/GentiumBookBasic-Regular.ttf
        - asset: assets/fonts/GentiumBook/GentiumBookBasic-Italic.ttf
          style: italic
        - asset: assets/fonts/GentiumBook/GentiumBookBasic-Bold.ttf
          weight: 700
        - asset: assets/fonts/GentiumBook/GentiumBookBasic-BoldItalic.ttf
          weight: 700
          style: italic
